build-haxe:
  stage: build
  image: haxe:3.4.7-alpine
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - haxe install-haxelibs.hxml
    - haxelib list
    - haxe build.hxml
  artifacts:
    paths:
      - www/js/BrowserMain.js
      - ServerMain.js

build-npm:
  stage: build
  image: alpine:3.8
  script:
    - apk add nodejs npm python make g++
    - npm install
  artifacts:
    paths:
      - node_modules

test:
  stage: test
  image: alpine:3.8
  services:
    - mysql:5.6
  variables:
    MYSQL_ROOT_PASSWORD: devroot
    MYSQL_DATABASE: giffon
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: $MYSQL_ROOT_PASSWORD
  script:
    - apk add nodejs npm mysql-client openjdk8-jre python3
    - mysql -h mysql -u root --password="$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" -e "source dev/initdb/giffon.sql"
    - npm start
    - sleep 3 # allow displaying some server init messages
    - pip3 install html5validator
    - html5validator --html http://localhost:3000
    - html5validator --css www/css/*.css
    - html5validator --svg --errors-only www/images/*.svg
    - npm stop

deploy-serverless:
  stage: deploy
  image: node:8-alpine
  script:
    - npm install -g serverless
    - serverless deploy --stage "${CI_COMMIT_REF_NAME}"
  only:
    - master
    - production
  except:
    - tags
    - schedules
