build-haxe:
  stage: build
  image: haxe:3.4.7-alpine
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - haxe install-haxelibs.hxml
    - haxelib list
    - haxe build.hxml
  artifacts:
    paths:
      - www/js/BrowserMain.js
      - ServerMain.js

build-npm:
  stage: build
  image: node:8-alpine
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

validate-markup:
  stage: test
  image: openjdk:8-jre-alpine
  script:
    - wget https://github.com/validator/validator/releases/download/18.8.29/vnu.jar_18.8.29.zip
    - unzip vnu.jar_18.8.29.zip
    - java -jar dist/vnu.jar --html www/*.html
    - java -jar dist/vnu.jar --css www/css/*.css
    - java -jar dist/vnu.jar --svg --errors-only www/images/*.svg

deploy-serverless:
  stage: deploy
  image: node:8-alpine
  script:
    - npm install -g serverless
    - serverless deploy --stage "${CI_COMMIT_REF_NAME}"
  only:
    - master
    - production
  except:
    - tags
    - schedules
