stages:
  - build
  - test-chrome
  # - test-firefox
  - deploy

.build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - apk add nodejs npm python make g++
    - npm install --unsafe-perm
    - npm run-script build-vendor-release
    - haxelib list
    - haxe build.hxml
    - haxe build-test.hxml
  artifacts:
    paths:
      - www/js/BrowserMain.js
      - www/js/BrowserMain.js.map
      - www/js/vendor.js
      - ServerMain.js
      - ServerMain.js.map
      - test/SeleniumTest.py
      - node_modules

build-haxe3:
  extends: .build
  image: haxe:3.4.7-alpine3.8

build-haxe4:
  extends: .build
  image: haxe:4.0.0-alpine3.8
  allow_failure: true

.test-selenium:
  image: alpine:3.8
  variables:
    MYSQL_ROOT_PASSWORD: devroot
    MYSQL_DATABASE: giffon
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: $MYSQL_ROOT_PASSWORD
  script:
    - apk add nodejs npm mysql-client openjdk8-jre python3 python3-dev openssl gcc libc-dev linux-headers
    # initialize mysql
    - mysql -h mysql -u root --password="$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" -e "source dev/initdb/01_giffon.sql"
    - mysql -h mysql -u root --password="$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" -e "source dev/initdb/02_giffon.sql"
    # figure out host container ip
    - cat /etc/hosts
    - export WEB_HOST="$(cat /etc/hosts | grep -Eo '^([0-9\.]*)\s+runner-[0-9a-f]+-project-[0-9a-f]+-concurrent-[0-9]+' | grep -Eo '^([0-9\.]*)')"
    - echo "${WEB_HOST}"
    # generate self-signed cert for https
    - cd dev/ssl
    - ./gen.sh "${WEB_HOST}"
    - cd ../..
    # test (validation)
    - npm start &
    - sleep 3 # allow displaying some server init messages
    - pip3 install html5validator
    - html5validator --html http://localhost:3000
    - html5validator --css www/css/*.css
    - html5validator --svg --errors-only www/images/*.svg
    # test (selenium)
    - pip3 install -r src/test/requirements.txt
    - python3 test/SeleniumTest.py
  artifacts:
    when: always
    paths:
      - test/errorShots

test-chrome:
  extends: .test-selenium
  dependencies:
    - build-haxe3
  stage: test-chrome
  services:
    - mysql:5.7
    - selenium/standalone-chrome:3.141.59-radium
  variables:
    BROWSER_NAME: chrome
    HUB_HOST: selenium-standalone-chrome

deploy-s3:
  stage: deploy
  dependencies:
    - build-haxe3
  image: python:alpine
  script:
    - pip install awscli
    - aws s3 sync --delete www "s3://static.giffon.io/${CI_COMMIT_REF_NAME}"
  only:
    - master
    - production
  except:
    - tags
    - schedules

deploy-serverless:
  stage: deploy
  dependencies:
    - build-haxe3
  image: node:8-alpine
  script:
    - npm install -g serverless@1.42.3
    - serverless deploy --stage "${CI_COMMIT_REF_NAME}"
  only:
    - master
    - production
  except:
    - tags
    - schedules
