build-browser:
  stage: build
  image: haxe:3.4.7-alpine
  script:
    - haxelib install build-browser.hxml --always
    - haxelib list
    - haxe build-browser.hxml
  artifacts:
    paths:
      - www/js/BrowserMain.js

build-server:
  stage: build
  image: haxe:3.4.7-alpine
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - haxelib dev hxnodejs lib/hxnodejs
    - haxelib dev hxnodelibs lib/hxnodelibs
    - haxelib install compiletime
    - haxelib install hashids
    - haxelib list
    - haxe build-server.hxml
  artifacts:
    paths:
      - ServerMain.js

validate-markup:
  stage: test
  image: openjdk:8-jre-alpine
  script:
    - wget https://github.com/validator/validator/releases/download/18.8.29/vnu.jar_18.8.29.zip
    - unzip vnu.jar_18.8.29.zip
    - java -jar dist/vnu.jar --html www/*.html
    - java -jar dist/vnu.jar --css www/css/*.css
    - java -jar dist/vnu.jar --svg --errors-only www/images/*.svg

deploy-serverless:
  stage: deploy
  image: node:8-alpine
  script:
    - npm install -g serverless
    - npm install
    - serverless deploy --stage "${CI_COMMIT_REF_NAME}"
  only:
    - master
    - production
  except:
    - tags
    - schedules
