service: giffon-web

app: giffon

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  environment:
    SERVERLESS_STAGE: ${opt:stage, 'dev'}
    DB_HOST: ${ssm:DB_HOST}
    DB_PASSWORD: ${ssm:DB_PASSWORD}
    DB_SALT: ${ssm:DB_SALT}
    DB_USER: ${ssm:DB_USER}
    STRIPE_SECKEY: ${ssm:STRIPE_SECKEY}
    SESSION_SECRET: ${ssm:SESSION_SECRET}
    FACEBOOK_CLIENT_ID: ${ssm:FACEBOOK_CLIENT_ID}
    FACEBOOK_APP_SECRET: ${ssm:FACEBOOK_APP_SECRET}
    GITHUB_CLIENT_ID: ${ssm:GITHUB_CLIENT_ID_${opt:stage, 'master'}}
    GITHUB_CLIENT_SECRET: ${ssm:GITHUB_CLIENT_SECRET_${opt:stage, 'master'}}
    TWITTER_CONSUMER_KEY: ${ssm:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${ssm:TWITTER_CONSUMER_SECRET}
    GITLAB_APP_ID: ${ssm:GITLAB_APP_ID}
    GITLAB_APP_SECRET: ${ssm:GITLAB_APP_SECRET}
    GOOGLE_CLIENT_ID: ${ssm:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${ssm:GOOGLE_CLIENT_SECRET}
    TWITCH_CLIENT_ID: ${ssm:TWITCH_CLIENT_ID}
    TWITCH_CLIENT_SECRET: ${ssm:TWITCH_CLIENT_SECRET}
    MAIL_PASSWORD: ${ssm:MAIL_PASSWORD}
    PT_HOST: ${ssm:PT_HOST}
    PT_PORT: ${ssm:PT_PORT}
    PAYPAL_CLIENT_ID: ${ssm:PAYPAL_CLIENT_ID}
    PAYPAL_CLIENT_SECRET: ${ssm:PAYPAL_CLIENT_SECRET}
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: "arn:aws:s3:::giffon-user/*"

package:
  patterns:
    - '!.envrc'
    - '!.devcontainer/**'
    - '!.haxelib/**'
    - '!chrome/**'
    - '!www/**'
    - '!private/**'
    - '!lib/**'
    - '!src/**'
    - '!test/**'
    - '!*.hxml'

functions:
  express:
    handler: handler.express
    events:
      - http:
          method: ANY
          path: '/'
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true
