package js.npm.validator;

@:jsRequire("validator")
extern class Validator {
    static public function contains(str:String, seed:String):Bool;
    static public function equals(str:String, comparison:String):Bool;
    static public function isAfter(str:String, ?date:Date):Bool;
    static public function isAlpha(str:String, ?locale:String):Bool;
    static public function isAlphanumeric(str:String, ?locale:String):Bool;
    static public function isAscii(str:String):Bool;
    static public function isBase64(str:String):Bool;
    static public function isBefore(str:String, ?date:Date):Bool;
    static public function isBoolean(str:String):Bool;
    static public function isByteLength(str:String, ?options:Dynamic):Bool;
    static public function isCreditCard(str:String):Bool;
    static public function isCurrency(str:String, ?options:Dynamic):Bool;
    static public function isDataURI(str:String):Bool;
    static public function isMagnetURI(str:String):Bool;
    static public function isDecimal(str:String, ?options:Dynamic):Bool;
    static public function isDivisibleBy(str:String, number:Float):Bool;
    static public function isEmail(str:String, ?options:Dynamic):Bool;
    static public function isEmpty(str:String, ?options:Dynamic):Bool;
    static public function isFQDN(str:String, ?options:Dynamic):Bool;
    static public function isFloat(str:String, ?options:Dynamic):Bool;
    static public function isFullWidth(str:String):Bool;
    static public function isHalfWidth(str:String):Bool;
    static public function isHash(str:String, algorithm:String):Bool;
    static public function isHexColor(str:String):Bool;
    static public function isHexadecimal(str:String):Bool;
    static public function isIdentityCard(str:String, ?locale:String):Bool;
    static public function isIP(str:String, ?version:Int):Bool;
    static public function isIPRange(str:String):Bool;
    static public function isISBN(str:String, ?version:Int):Bool;
    static public function isISSN(str:String, ?options:Dynamic):Bool;
    static public function isISIN(str:String):Bool;
    static public function isISO8601(str:String):Bool;
    static public function isRFC3339(str:String):Bool;
    static public function isISO31661Alpha2(str:String):Bool;
    static public function isISO31661Alpha3(str:String):Bool;
    static public function isISRC(str:String):Bool;
    static public function isIn(str:String, values:Array<String>):Bool;
    static public function isInt(str:String, ?options:Dynamic):Bool;
    static public function isJSON(str:String):Bool;
    static public function isJWT(str:String):Bool;
    static public function isLatLong(str:String):Bool;
    static public function isLength(str:String, ?options:Dynamic):Bool;
    static public function isLowercase(str:String):Bool;
    static public function isMACAddress(str:String):Bool;
    static public function isMD5(str:String):Bool;
    static public function isMimeType(str:String):Bool;
    static public function isMobilePhone(str:String, ?locale:String, ?options:Dynamic):Bool;
    static public function isMongoId(str:String):Bool;
    static public function isMultibyte(str:String):Bool;
    static public function isNumeric(str:String, ?options:Dynamic):Bool;
    static public function isPort(str:String):Bool;
    static public function isPostalCode(str:String, locale:String):Bool;
    static public function isSurrogatePair(str:String):Bool;
    static public function isURL(str:String, ?options:Dynamic):Bool;
    static public function isUUID(str:String, ?version:Int):Bool;
    static public function isUppercase(str:String):Bool;
    static public function isVariableWidth(str:String):Bool;
    static public function isWhitelisted(str:String, chars:String):Bool;
    static public function matches(str:String, pattern:haxe.extern.EitherType<String, EReg>, ?modifiers:String):Bool;
    static public function blacklist(input:String, chars:String):String;
    static public function escape(input:String):String;
    static public function unescape(input:String):String;
    static public function ltrim(input:String, ?chars:String):String;
    static public function normalizeEmail(email:String, ?options:Dynamic):String;
    static public function rtrim(input:String, ?chars:String):String;
    static public function stripLow(input:String, ?keep_new_lines:Bool):String;
    static public function toBoolean(input:String, ?strict:Bool):Bool;
    static public function toDate(input:String):Date;
    static public function toFloat(input:String):Float;
    static public function toInt(input:String, ?radix:Int):Int;
    static public function trim(input:String, ?chars:String):String;
    static public function whitelist(input:String, chars:String):String;
}